name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  windows-build:
    name: Windows build
    uses: ./.github/workflows/windows_build.yml

  linux-build:
    name: Linux build
    uses: ./.github/workflows/linux_build.yml

  macos-build:
    name: macOS build
    uses: ./.github/workflows/macos_build.yml

  ios-build:
    name: iOS build
    uses: ./.github/workflows/ios_build.yml

  android-build:
    name: Android build
    uses: ./.github/workflows/android_build.yml

  html5-build:
    name: HTML5 build
    uses: ./.github/workflows/html5_build.yml

  package:
    name: Package plugin
    runs-on: ubuntu-latest
    needs: [windows-build, linux-build, macos-build, ios-build, android-build, html5-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download Windows artifacts
        uses: actions/download-artifact@v8
        with:
          name: pixelpart-windows
          path: artifacts/windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v8
        with:
          name: pixelpart-linux
          path: artifacts/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v8
        with:
          name: pixelpart-macos
          path: artifacts/macos

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-ios
          path: artifacts/ios

      - name: Download Android artifacts
        uses: actions/download-artifact@v8
        with:
          name: pixelpart-android
          path: artifacts/android

      - name: Download HTML5 artifacts
        uses: actions/download-artifact@v8
        with:
          name: pixelpart-html5
          path: artifacts/html5

      - name: Display downloaded artifacts
        run: ls -R artifacts

      - name: Copy binaries
        run: |
          cp -r artifacts/windows/*.dll ./pixelpart-plugin/extensions/Pixelpart/
          cp -r artifacts/linux/*.so ./pixelpart-plugin/extensions/Pixelpart/
          cp -r artifacts/macos/*.dylib ./pixelpart-plugin/extensions/Pixelpart/
          mkdir -p ./pixelpart-plugin/extensions/Pixelpart/iOSSourceFromMac/
          cp -r artifacts/ios/*.zip ./pixelpart-plugin/extensions/Pixelpart/iOSSourceFromMac/
          mkdir -p ./pixelpart-plugin/extensions/Pixelpart/AndroidSource/libs/x86_64/
          mkdir -p ./pixelpart-plugin/extensions/Pixelpart/AndroidSource/libs/arm64-v8a/
          mkdir -p ./pixelpart-plugin/extensions/Pixelpart/AndroidSource/libs/armeabi-v7a/
          cp -r artifacts/android/x86_64/*.so ./pixelpart-plugin/extensions/Pixelpart/AndroidSource/libs/x86_64/
          cp -r artifacts/android/arm64-v8a/*.so ./pixelpart-plugin/extensions/Pixelpart/AndroidSource/libs/arm64-v8a/
          cp -r artifacts/android/armeabi-v7a/*.so ./pixelpart-plugin/extensions/Pixelpart/AndroidSource/libs/armeabi-v7a/
          cp -r artifacts/html5/*.js ./pixelpart-plugin/extensions/Pixelpart/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-plugin-gamemaker
          path: ./pixelpart-plugin
