name: HTML5 build
on:
  workflow_call:

jobs:
  build-html5:
    runs-on: ubuntu-22.04
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Cache emsdk
        id: cache
        uses: actions/cache@v5
        with:
          path: ./emsdk
          key: ${{ runner.os }}-emsdk-3_1_47-v1

      - name: Install emsdk
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install 3.1.47

      - name: Compile
        run: |
          ./emsdk/emsdk activate 3.1.47
          source ./emsdk/emsdk_env.sh
          emcmake cmake --preset html5-wasm
          cmake --build build/html5-wasm --target install --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-html5
          path: ./pixelpart-plugin/extensions/Pixelpart/libpixelpartgm.js
